### ISSUE TITLE
Rearrange the order of created feeds

### ISSUE THREAD

**Issue by claudiotassis** [gravitywiz/gravityforms-openai#10]
There's no option to "drag-and-drop" the created feeds. In other words, once you've created a feed, you cannot change its order. If you create a feed that depends on a different one, the answer will not be generated based on that dependency, since the prompt for that hasn't been created yet.
Example:
You have 3 different feeds: 
1. Question
2. Text
3. Answer

Feed 1 prompts for a generated question based on the text generated in feed 2. 
The question will end up being randomly generated because the text hasn't been generated yet.
However, if feed 1 is the TEXT, the question will be generated according to the text.
How to fix it? Make it possible to drag and drop the created fields, making it possible to rearrange the order.

**Comment by bi1101** [comment]
Yeah this problem bugs me too!

**Comment by spivurno** [comment]
Hey @claudiotassis, I replied to your comment on the blog:

https://gravitywiz.com/gravity-forms-openai/comment-page-2/#comment-871971

I've left this is feature request open for others to weigh in on.

**Comment by claygriffiths** [comment]
Apologies for the delay getting to this!

This has been added in [1.0-beta-1.5](https://github.com/gravitywiz/gravityforms-openai/releases/tag/1.0-beta-1.5). 

We appreciate the feedback. 🙏
