### ISSUE TITLE
Live preview of Open AI Feed in confirmation message

### ISSUE THREAD

**Issue by bi1101** [gravitywiz/gravityforms-openai#12]
Hi developers,

I' very thankyou for your hard work on this project and for making it available for free. Although I understand that support may not be possible, I would greatly appreciate any assistance you can provide.

As a teacher, I am currently creating an auto-grading system for essays at my English center. The workflow for this project involves these steps:
Step 1: users submitting an essay and a question, 
Step 2: receiving a confirmation message with feedback inserted.

However, I have encountered a problem where the feedback response takes too long (1-3 minutes) due to the setup of multiple Open AI feeds. As a result, users are stuck on Step 1 for an extended period of time. Is there a way to make the user transition to the confirmation page immediately and wait for the live OpenAI feed there?

I am considering purchasing the AnywhereTag from GravityWiz if this can solve this issue. Thank you for your help in advance!

**Comment by spivurno** [comment]
Hey @bi1101! General functionality questions are better suited to either the plugin page (https://gravitywiz.com/gravity-forms-openai/) or our pre-sales form: 

https://gravitywiz.com/have-a-question-about-gravity-perks/

Closing this but look forward to helping in either of those locations. 🙂
