### ISSUE TITLE
AND - NO after each conditional would bring extra condition options

### ISSUE THREAD

**Issue by claudiotassis** [gravitywiz/gravityforms-openai#15]
Is there any chance you would implement the options OR - AND  after each condition?

<img width="509" alt="no or and" src="https://user-images.githubusercontent.com/65249675/236339620-cb78b41a-c4ad-4cdd-9394-65cf7af69fee.png">

**Comment by spivurno** [comment]
We're somewhat constrict by Gravity Forms here as we're using the GF Feed Add-on framework for this. To add support for and/or logic, we'd have to implement our own conditional logic which is not certainly not impossible but would be a bit of chore. Not something we'll be pursuing in the short term.

I'm not certain that this plugin supports feed conditional logic but it may be worth a shot:

https://mcdonnell.nz/product/gravity-forms-advanced-conditional-logic/
