### ISSUE TITLE
Critical Error on update

### ISSUE THREAD

**Issue by UrbanChangeLab** [gravitywiz/gravityforms-openai#7]
Hello, I get this fatal error with the Beta 1 Version when clicking at the WP Plugins Update Link
"
Fatal error: Uncaught Error: Class "GWiz_GF_OpenAI\Dependencies\WP_Error" not found in /usr/www/users/urbanci/wp-content/plugins/gravityforms-openai/third-party/inc2734/wp-github-plugin-updater/src/App/Model/GitHubReleases.php:109 Stack trace: #0 /usr/www/users/urbanci/wp-content/plugins/gravityforms-openai/third-party/inc2734/wp-github-plugin-updater/src/App/Model/GitHubReleases.php(64): GWiz_GF_OpenAI\Dependencies\Inc2734\WP_GitHub_Plugin_Updater\App\Model\GitHubReleases->_retrieve() #1 /usr/www/users/urbanci/wp-content/plugins/gravityforms-openai/third-party/inc2734/wp-github-plugin-updater/src/Bootstrap.php(112): GWiz_GF_OpenAI\Dependencies\Inc2734\WP_GitHub_Plugin_Updater\App\Model\GitHubReleases->get() #2 /usr/www/users/urbanci/wp-includes/class-wp-hook.php(310): GWiz_GF_OpenAI\Dependencies\Inc2734\WP_GitHub_Plugin_Updater\Bootstrap->_pre_set_site_transient_update_plugins() #3 /usr/www/users/urbanci/wp-includes/plugin.php(205): WP_Hook->apply_filters() #4 /usr/www/users/urbanci/wp-includes/option.php(2018): apply_filters() #5 /usr/www/users/urbanci/wp-includes/update.php(391): set_site_transient() #6 /usr/www/users/urbanci/wp-includes/class-wp-hook.php(308): wp_update_plugins() #7 /usr/www/users/urbanci/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #8 /usr/www/users/urbanci/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /usr/www/users/urbanci/wp-admin/admin.php(385): do_action() #10 /usr/www/users/urbanci/wp-admin/plugins.php(10): require_once('/usr/www/users/...') #11 {main} thrown in /usr/www/users/urbanci/wp-content/plugins/gravityforms-openai/third-party/inc2734/wp-github-plugin-updater/src/App/Model/GitHubReleases.php on line 109

There has been a critical error on this website. Please check your site admin email inbox for instructions.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

**Comment by spivurno** [comment]
Fixed!
